# Generated by Django 5.2.5 on 2025-10-15 00:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='مقتطف الكود')),
                ('question_type', models.CharField(choices=[('single', 'اختيار واحد'), ('multiple', 'اختيار متعدد'), ('true_false', 'صح أو خطأ')], default='single', max_length=20, verbose_name='نوع السؤال')),
                ('points', models.IntegerField(default=1, verbose_name='النقاط')),
                ('explanation', models.TextField(blank=True, verbose_name='الشرح')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500, verbose_name='نص الإجابة')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاختبار')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=10, verbose_name='مستوى الصعوبة')),
                ('duration', models.IntegerField(default=30, verbose_name='المدة (بالدقائق)')),
                ('pass_percentage', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='النسبة المطلوبة للنجاح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz_app.category', verbose_name='الفئة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz', verbose_name='الاختبار'),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='النتيجة')),
                ('total_points', models.IntegerField(default=0, verbose_name='مجموع النقاط')),
                ('percentage', models.FloatField(default=0, verbose_name='النسبة المئوية')),
                ('passed', models.BooleanField(default=False, verbose_name='نجح')),
                ('time_taken', models.IntegerField(default=0, verbose_name='الوقت المستغرق (بالثواني)')),
                ('completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz_app.quiz', verbose_name='الاختبار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نتيجة اختبار',
                'verbose_name_plural': 'نتائج الاختبارات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحيحة')),
                ('points_earned', models.IntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question', verbose_name='السؤال')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz_app.quizresult', verbose_name='نتيجة الاختبار')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.answer', verbose_name='الإجابة المختارة')),
            ],
            options={
                'verbose_name': 'إجابة المستخدم',
                'verbose_name_plural': 'إجابات المستخدمين',
                'unique_together': {('quiz_result', 'question')},
            },
        ),
    ]
